name: CI
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate CocoaPod
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPOD_PASSWORD_LOGIN }}
        run: |
          pod spec lint VietMapNavigation.podspec --allow-warnings
      - name: Publish to CocoaPod register
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPOD_PASSWORD_LOGIN }}
        run: |
          pod trunk push VietMapNavigation.podspec --allow-warnings
